spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cloud
    password: Cloud@2023
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true